
<style>
    .visible-mobile{display:block;}
    .col-md-3 {
        float: left;
    /*  width: 21%;*/
        margin-top: 40px;
    }
    .col-md-4 {
        float: left;
        width: 24%;
    }
    .col-md-5 {
/*      float: left; */
        width: 33.33%;
    }
    @media (max-width:768px){
        .col-md-3,.col-md-4, .col-md-5 {
            width: 100% !important;
            text-align:right;
            margin-top:-20px;
        }
    }
    @media screen and (min-width:980px){
        .visible-mobile{
            display:none;
        }
    }
</style>
<div class="container">
    <?php 
    $banner1 = Mage::getStoreConfig('onestepcheckout/config/page_banner1');
    $banner2 = Mage::getStoreConfig('onestepcheckout/config/page_banner2');
    $banner3 = Mage::getStoreConfig('onestepcheckout/config/page_banner3'); 
    ?>
    <?php if($banner1):?>
    <div class="col-md-3 cart-3-banners">
        <img src="<?php echo $banner1 ?>"/>
    </div>
    <?php endif; ?>
    <?php if($banner2):?>
    <div class="col-md-3 cart-3-banners">
        <img src="<?php echo $banner2 ?>"/>
    </div>
    <?php endif; ?>
    <?php if($banner3):?>
    <div class="col-md-3 cart-3-banners">
        <img src="<?php echo $banner3 ?>"/>
    </div>
    <?php endif; ?>
    <div  class="col-md-5">
<?php $islogin = (Mage::getSingleton('customer/session')->isLoggedIn()) ? 1 : 0; ?>
    <hidden value="Welcome to One Step Checkout Pro"></hidden>
    <hidden value="Please enter your details below to complete your purchase."></hidden>
    <?php $temp_session = Mage::helper('onestepcheckout')->checkSession(); ?>
    <input type="hidden" value="<?php echo $temp_session ?>" id="check_session"/>
    <h1 class="mw-osc-page-tittle"><?php echo $this->__(Mage::getStoreConfig('onestepcheckout/config/page_title'))?></h1>
    <p class="mw-osc-page-content"><?php echo $this->__(Mage::getStoreConfig('onestepcheckout/config/page_content'))?></p>
    <div id="message-box">
        <?php if(Mage::getSingleton('core/session')->getErrorpayment()!=""):?>
        <div class="error-msg" style="magin-bottom:10px;">
            <?php echo Mage::getSingleton('core/session')->getErrorpayment();?>
        </div>
        <?php endif;?>
        <?php echo $this->getMessagesBlock()->getGroupedHtml()?>
    </div>
    <?php if(!$islogin):?>
        <?php if(Mage::getStoreConfig('onestepcheckout/config/enable_quicklogin')):?>
        <a id="loginbox" href="#inline1" title=""><?php echo $this->__('Already registered? Click here to login.');?></a>
        <?php endif?>
    <?php endif?>
    </div>
</div>
    <div class="mw-osc-threecolumns mw-osc-checkoutcontainer mw-osc-skin-generic">
        <form data-key="<?php echo Mage::getSingleton('core/session')->getFormKey();?>" id="onestep_form" action="<?php echo $this->getUrl('onestepcheckout/index/updateordermethod')?>" method="POST">
            <?php /*?><div class="clearfix">
                <div class="mw-osc-column-2">
                    <?php 
                    $banner1 = Mage::getStoreConfig('onestepcheckout/config/page_banner1');
                    $banner2 = Mage::getStoreConfig('onestepcheckout/config/page_banner2');
                    $banner3 = Mage::getStoreConfig('onestepcheckout/config/page_banner3');
                    ?>
                    <?php if($banner1):?>
                    <div  class="col-md-5 visible-desktop">
                        <img src="<?php echo $banner1 ?>"/>
                    </div>
                    <?php endif; ?>
                    <?php if($banner2):?>
                    <div  class="col-md-5 visible-desktop">
                        <img src="<?php echo $banner2 ?>"/>
                    </div>
                    <?php endif; ?>
                    <?php if($banner3):?>
                    <div  class="col-md-5 visible-desktop">
                        <img src="<?php echo $banner3 ?>"/>
                    </div>
                    <?php endif; ?>
                </div>
            </div><?php */?>
            <div class="mw-osc-column mw-osc-column-left">
                <div class="mw-osc-block">
                    <div class="mw-osc-block-title">
                        <p class="onestepcheckout-numbers onestepcheckout-numbers-1">
                            <?php echo $this->__('Billing address');?>
                        </p>
                    </div>
                    <div class="mw-osc-block-content">
                        <div>
                            <?php echo $this->getChildHtml('billing');?>
                        </div>
                    </div>

                    <?php if(!Mage::helper('onestepcheckout')->onlyProductDownloadable()):?>
                    <?php if(Mage::getStoreConfig('onestepcheckout/config/allowshippingotheraddress')):?>
                    <div style="display:none;" id="shipping_show">
                        <div class="mw-osc-block-title">
                            <p class="onestepcheckout-numbers onestepcheckout-numbers-2" >
                                <?php echo $this->__('Shipping address');?>
                            </p>
                        </div>
                        <div class="mw-osc-block-content">
                            <div>
                                <?php echo $this->getChildHtml('shipping');?>
                            </div>
                        </div>
                    </div>
                    <?php endif;?>
                    <?php endif;?>
                </div>
            </div>
            <!-- end .mw-osc-column-left -->
            <div class="mw-osc-column-2">
                <div id="mw-osc-column-container">
                <?php if(!Mage::helper('onestepcheckout')->onlyProductDownloadable()):?>
                    <div class="mw-osc-column mw-osc-column-middle">
                        <div class="mw-osc-block">
                            <div class="mw-osc-block-title">
                                <p class="onestepcheckout-numbers onestepcheckout-numbers-2" id="mw-osc-p2">
                                    <?php echo $this->__('Shipping method');?>
                                </p>
                            </div>
                            <?php echo $this->getChildHtml('shipping_method');?>
                        </div>
                    </div>
                <?php endif?>
                    <div class="mw-osc-column  mw-osc-column-right" >
                        <div class="section allow mw-osc-block" id="opc-payment">
                            <div class="mw-osc-block-title" >
                                <p <?php if(Mage::helper('onestepcheckout')->onlyProductDownloadable())
                                          echo "class='onestepcheckout-numbers onestepcheckout-numbers-2' id='mw-osc-p2'";
                                          else
                                          {
                                          if(Mage::getStoreConfig("onestepcheckout/deliverydate/allow_options"))
                                          echo "class='onestepcheckout-numbers onestepcheckout-numbers-4' id='mw-osc-p4'";
                                          else echo "class='onestepcheckout-numbers onestepcheckout-numbers-3' id='mw-osc-p3'";
                                          }?>>
                                          <?php echo $this->__('Payment method');?>
                                </p>
                            </div>
                                <div class="mw-osc-block-content" >
                                    <div id="checkout-step-payment" class="step a-item" >
                                    <?php echo $this->getChildHtml('payment');?>
                                    </div>
                                </div>
                        </div>
                    </div>
                    <div class="clear_both">&nbsp;</div>
                </div>
            </div>

            <?php if (Mage::helper('onestepcheckout')->isDDateRunning())
                {?>
                    <div class="review">
                        <div class="mw-osc-block">
                            <div class="mw-osc-block-title">
                                <p class="onestepcheckout-numbers onestepcheckout-numbers-4">
                                    <?php echo $this->__('Delivery Time');?>
                                </p>
                            </div>
                            <?php echo $this->getChildHtml('ddate');?>
                        </div>
                    </div>
            <?php } ?>
            <!-- end.mw-osc-column-2 -->
            <div class="review">
                <div class="mw-osc-block">
                    
                    <?php echo $this->getChildHtml('review');?>
                </div>
            </div>
            <!-- end.review -->
            <div class="clear_both"></div>
        </form>

        <?php if(version_compare(Mage::getVersion(),'1.4.0.1','>='))://fix cho magento >= 1.4?>
                <div style="display: none;">
<!--                        <div id="inline1" style="height:250px;overflow:auto;">-->
                    <div id="inline1" style="height:240px;">
                        <?php echo $this->getChildHtml('login');?>
                    </div>
                    <div id="inline3" style="height:210px;overflow:auto;">
                        <?php echo $this->getChildHtml('forgotpassword');?>
                    </div>
                    <div id="inline2" style="width:<?php echo Mage::getStoreConfig('onestepcheckout/termcondition/boxwidth')?>;height:<?php echo Mage::getStoreConfig('onestepcheckout/termcondition/boxheight')?>;overflow:auto;">
                        <div class="mw-osc-title-login">
                            <h1><?php echo $this->__('Terms and Conditions');?> </h1>
                        </div>
                        <div class="mw-osc-ct-term" style="height: <?php echo (Mage::getStoreConfig('onestepcheckout/termcondition/boxheight')-90).'px';?>">
                            <?php $condition = $this->__(Mage::getStoreConfig('onestepcheckout/termcondition/select_term_conditions'));
                            if($condition!=0){
                                    $temp = Mage::getModel('onestepcheckout/system_config_source_term')->getTermById($condition);
                                echo $temp;
                            }else{
                                echo $this->__(Mage::getStoreConfig('onestepcheckout/termcondition/content_options'));
                            }

                            ?>
                        </div>
                    </div>
                </div>
        <?php else:?>
                <div style="display: none;">
                    <div id="inline1">
                        <?php echo $this->getChildHtml('login');?>
                    </div>
                    <div id="inline3" style="height:205px;overflow:auto;">
                        <?php echo $this->getChildHtml('forgotpassword');?>
                    </div>
                    <div id="inline2" style="width:<?php echo Mage::getStoreConfig('onestepcheckout/termcondition/boxwidth')?>;height:<?php echo Mage::getStoreConfig('onestepcheckout/termcondition/boxheight')?>;overflow:auto;">
                        <h1><?php echo $this->__('Terms and Conditions');?> </h1>
                        <br />
                        <?php echo $this->__(Mage::getStoreConfig('onestepcheckout/termcondition/content_options'));?>
                    </div>
                </div>
        <?php endif;?>
        </div>
    <div class="clear_both">&nbsp;</div>
    <div style="left: 0px; min-height: 710px; display: none; top:0px;" id="loading-mask">
        <p id="loading_mask_loader" class="loader"><img alt="Loading..." src="<?php echo $this->getSkinUrl('mw_onestepcheckout/images/ajax-loader-tr.gif')?>"></p>
    </div>

    <style>
        div.ui-datepicker{
            font-size:16px;
            width: 20em;
        }
        .ui-datepicker td span,
        .ui-datepicker td a{
            font-size: 12px;
        }

        .ui-datepicker td span:after,
        .ui-datepicker td a:after
        {
            content: "";
            display: block;
            font-size: 10px;
            width: 38px;
            overflow: hidden;
            margin: 0;
            padding: 0;
            text-align: right;
            color: green;
            direction: ltr;
            min-height: 20px;
        }
        .ui-datepicker td{
            position: relative;
        }

        .ui-state-default, .ui-widget-content .ui-state-default{
            border: none;
        }

        .ui-datepicker td{
            background: #5ba8e9;
            border: 1px solid #cccccc;
        }
        .ui-datepicker-other-month, .ui-widget-content .ui-datepicker-other-month{
            background: transparent;
        }

        .ui-datepicker table{
            font-size: 0.9em;
        }

    </style>


    <?php

    if(Mage::helper('core')->isModuleEnabled('Dreamcode_Shippingrule') && Mage::helper('core')->isModuleOutputEnabled('Dreamcode_Shippingrule'))
    {
        if(Mage::getStoreConfig('dcshippingrule/general/allow') == 1) {
            $enable_module_shipping_fee = Mage::getStoreConfig('dcshippingrule/general/allow');
     ?>
    <div style="display: none;">
        <div id="extra_shipping_for_delivery_date" style="overflow:auto;">

                <script type="text/javascript">
                    <?php

                $baseCurrencyCode = Mage::app()->getStore()->getBaseCurrencyCode();
                $currentCurrencyCode = Mage::app()->getStore()->getCurrentCurrencyCode();


                $slot_time = Mage::app()->getStore($scopeId)->getConfig('dcshippingrule/general/fee_same_day_enable_by_slot_time');
                
                $start_time = strtotime( $today );
                $end_time = strtotime( $nextDate );

                if($slot_time != 0) {
                    $slot_time = explode("-", $slot_time);
                    $start_time = strtotime( $today . ' ' . $slot_time[0] );
                    $end_time = strtotime( $today . ' ' . $slot_time[1] );
                }
                
                $slot_time_now = strtotime("now");
                //echo ($slot_time_now .' '. $start_time .' '. $end_time) .'<br>'; 

                if($slot_time_now >= $start_time &&  $slot_time_now <= $end_time){
                    $fee_same_day = Mage::app()->getStore($scopeId)->getConfig('dcshippingrule/general/fee_same_day');
                }else{
                    $fee_same_day = 0;
                }

                echo "window.onestepConfig.delivery.fee_same_day = '" . $fee_same_day ."'; ";
                echo "window.onestepConfig.delivery.fee_for_same_day = '" . Mage::helper('directory')->currencyConvert(Mage::app()->getStore($scopeId)->getConfig('dcshippingrule/general/fee_for_same_day'), $baseCurrencyCode, $currentCurrencyCode) ."'; ";
                
                echo "window.onestepConfig.delivery.fee_next_day = '" . Mage::app()->getStore($scopeId)->getConfig('dcshippingrule/general/fee_next_day') ."'; ";
                echo "window.onestepConfig.delivery.next_day = '" . Date('d/m/Y', strtotime('+1 day')) ."'; ";
                echo "window.onestepConfig.delivery.fee_for_next_day = '" . Mage::helper('directory')->currencyConvert(Mage::app()->getStore($scopeId)->getConfig('dcshippingrule/general/fee_for_next_day'), $baseCurrencyCode, $currentCurrencyCode) ."'; ";
                
                echo "window.onestepConfig.delivery.current_currency_code = '" . Mage::app()->getLocale()->currency( $currentCurrencyCode )->getSymbol() ."'; ";

                $special_days_data = unserialize(Mage::app()->getStore($scopeId)->getConfig('dcshippingrule/general/special_days'));
                if(!empty($special_days_data)){
                    foreach ( $special_days_data as $key => $value) {
                        $special_days_data[$key]['fee'] = Mage::helper('directory')->currencyConvert($value['fee'], $baseCurrencyCode, $currentCurrencyCode);
                    }
                    echo "window.onestepConfig.delivery.special_days = '" . json_encode($special_days_data) ."'; ";
                    echo "window.onestepConfig.delivery.current_day = '" . date('d/m/Y', Mage::getModel('core/date')->gmtTimestamp()) ."'; ";
                }
                    ?>
                </script>

            <h3><?php echo $this->__('Extra shipping fee for delivery date') . " " ;?> <span id="extra_shipping_note_for_delivery_date"></span></h3>
            <p>
                <span style="display: none;" id="dc_curent_delivery_date"><?php echo date('d/m/Y', Mage::getModel('core/date')->gmtTimestamp()); ?></span>
                <p><?php echo $this->__('Fee: '); ?><span id="extra_shipping_fee_for_delivery_date">0</span></p>
            </p>
            
        </div>
    </div>

    <?php 
        }else{
            $enable_module_shipping_fee = 0;
        }
    }else{
        $enable_module_shipping_fee = 0;
    }
    ?>

    <script type="text/javascript">
    <?php
        echo "window.onestepConfig.delivery.enable_module_shipping_fee = '" . $enable_module_shipping_fee  ."'; ";
    ?>
    </script>
